name: Angular CI

# Run this workflow on push or pull request events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs
jobs:
  build:
    # Specify the operating system
    runs-on: ubuntu-latest

    # Define the steps for the build job
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js 18 for Angular 18
          cache: 'npm'

      # Step 3: Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run unit tests
      - name: Run unit tests
        run: ng test --watch=false --no-progress

      # Step 6: Build the Angular project
      - name: Build Angular app
        run: npm run build -- --prod

      # Step 7: Optionally deploy to GitHub Pages (optional)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/my-angular-app
