name: Angular and GraphQL CI

on:
  push:
    branches:
      - master

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install Angular CLI globally
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      # Step 4: Install root dependencies
      - name: Install root dependencies
        run: npm install

      # Step 5: Install dependencies for GraphQL server
      - name: Install GraphQL server dependencies
        run: npm install --prefix ./server

      # Step 6: Run Angular unit tests
      - name: Run Angular unit tests
        run: |
          export CHROME_BIN=/usr/bin/google-chrome-stable
          ng test --watch=false --no-progress --browsers=ChromeHeadless

      # Step 7: Run GraphQL server tests
      - name: Run GraphQL server tests
        run: npm run test --prefix ./server

      # Step 8: Set baseHref in angular.json for production build
      - name: Set baseHref for Angular build
        run: |
          jq '.projects["cus-transaction-app"].architect.build.options.baseHref = "/cus-transaction-app/"' angular.json > angular.json.tmp && mv angular.json.tmp angular.json

      # Step 9: Build Angular app
      - name: Build Angular app
        run: ng build --configuration production

      # Step 10: Build GraphQL server
      - name: Build GraphQL server
        run: npm run build --prefix ./server

      # Step 11: Organize files for deployment
      - name: Prepare deployment folder
        run: |
          mkdir -p deploy/server
          cp -R dist/cus-transaction-app/browser/* deploy/
          cp -R server/dist/* deploy/server/

      # Step 12: Deploy Angular and GraphQL together
      - name: Deploy Angular and GraphQL
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: prod
          token: ${{ secrets.GITHUB_TOKEN }}
