name: Angular CI

# Run this workflow on push or pull request events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define Env
env:
  ACTIONS_STEP_DEBUG: true  # Enable step debugging for more verbose logs

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install Angular CLI globally
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Install Chrome (for headless testing)
      - name: Install Google Chrome
        run: |
          curl -sS https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo dpkg -i google-chrome.deb
          sudo apt-get install -f

      # Step 6: Run unit tests (use ChromeHeadless for headless testing)
      - name: Run unit tests
        run: |
          export CHROME_BIN=/usr/bin/google-chrome-stable
          ng test --watch=false --no-progress --browsers=ChromeHeadless

      # Step 7: Build the Angular app
      - name: Build Angular app
        run: ng build --configuration production

      # Step 8: Ensure dist folder exists
      - name: Check if dist folder exists
        run: |
          if [ ! -d "dist/cus-transaction-app" ]; then
            echo "Build directory does not exist!";
            exit 1;
          fi

      # Step 9: Set up gh-pages branch (ensure it's initialized)
      - name: Set up gh-pages branch
        run: |
          git fetch --all
          git checkout gh-pages || git checkout --orphan gh-pages  # Ensure it's created correctly
          git reset --hard
          echo "Initialized gh-pages branch."

      # Debug: List contents of dist folder
      - name: Debug - List contents of dist folder
        run: |
          echo "Listing contents of dist folder"
          ls -R dist/

      # Step 10: Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          BRANCH: prod
          BASE_BRANCH: master
          FOLDER: dist/cus-transaction-app/browser  # Ensure this is the correct path
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure this is correct.

      # Step 11: Clean up (reset any changes to avoid conflicts)
      - name: Clean up (reset the repository to avoid any conflicts)
        run: |
          git checkout master
          git reset --hard
